controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

transactions:
    path: /transactions
    controller: App\Controller\TeamController::teamTransactions
